### ISSUE TITLE
Adding VPN watch support

### ISSUE THREAD

**Issue by chaise** [Neutrinet/carnet_rose#1]
It might be nice to be abble to follow the VPN billing as well. 
So adding VPN: yes/no, Last payment date, Late: yes/no.

**Comment by chaise** [comment]
It might be nice to know see imediately when someone membership is due.
Late for membership: yes/no.

**Comment by Psycojoker** [comment]
Done (but only for VPN part, for payment @wannes-ds is working on billy)
