### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by chaise** [Neutrinet/carnet_rose#3]
In carnet_rose/settings.py, two things shouldn't be in a production environment:
SECRET_KEY
DEBUG

**Comment by Psycojoker** [comment]
If you look here https://github.com/Neutrinet/carnet_rose/blob/c55403e5754cf35e5f80148e32c3b931d8aede89/carnet_rose/settings.py#L92  you'll see that we can import a settings_local, this is used to overwrite SECRET_KEY and DEBUG in prod (this is a classic pattern in django deployment).
